---
name: rules-pact
on:
  push:
    branches:
      - main
jobs:
  test_job:
    runs-on: ubuntu-20.04
    container:
      image: gcr.io/bazel-public/bazel:6.3.2
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
      options: -e USER="root" -u="root"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch bazel cache
        uses: actions/cache@v3
        with:
          path: /tmp/cache
          key: bazel-cache
          restore-keys: |
            bazel-cache
      - name: Bazel test
        run: bazel --output_user_root=/tmp/cache test --test_output=errors //...
  release_job:
    runs-on: ubuntu-20.04
    needs: test_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: FETCH THE SOURCE ARCHIVE
        run: |
          curl \
            -L \
            -o rules_pact-v1.1.4.tar.gz \
            https://github.com/opicaud/rules_pact/archive/refs/tags/v1.1.4.tar.gz
      - name: CREATE RELEASE
        id: create-release
        uses: ncipollo/release-action@v1.13.0
        with:
          name: rules_pact v1.1.4
          tag: v1.1.4
          allowUpdates: true
          draft: true
          artifactErrorsFailBuild: true
          updateOnlyUnreleased: true
          generateReleaseNotes: false
          artifacts: >-
            rules_pact-v1.1.4.tar.gz